# Generated by Django 5.2 on 2025-04-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_alter_post_created'),
        ('profiles', '0002_remove_profiles_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
